# Generated by Django 5.2.4 on 2025-07-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_sensorcategory_rename_bulding_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='description',
        ),
    ]
